apiVersion: v1
kind: Secret
metadata:
  name: nestjs-redis
type: Opaque
data:
  # echo -n 'Ug6jyOgHiQ8lPdOVc8htZnaCdg2MJqFhJvhuq3be' | base64
  NASA_API_KEY: VWc2anlPZ0hpUThsUGRPVmM4aHRabmFDZGcyTUpxRmhKdmh1cTNiZQ==