apiVersion: v1
kind: Service
metadata:
  name: nestjs-redis
spec:
  selector:
    app: nestjs-redis
  type: NodePort
  ports:
  - name: nestjs-redis
    port: 8081
    protocol: TCP
    nodePort: 30320